default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: facebook_clone_app_development

test:
  <<: *default
  database: facebook_clone_app_test

production:
  <<: *default
  database: facebook_clone_app_production
  username: facebook_clone_app
  password: <%= ENV['FACEBOOK_CLONE_APP_DATABASE_PASSWORD'] %>
